### ISSUE TITLE
Using `InternalsVisibleTo` MSBuild items is now supported out of the box by the .NET SDK

### ISSUE THREAD

**Issue by 0xced** [SixLabors/SharedInfrastructure#25]
Since .NET 5, using `InternalsVisibleTo` MSBuild items is [supported out of the box](https://github.com/dotnet/sdk/blob/v5.0.102/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L108-L112) thanks to https://github.com/dotnet/sdk/pull/3439. It means that the [SixLabors.Global.targets](https://github.com/SixLabors/SharedInfrastructure/blob/b78033943069b6c0e1762ed54855b4e1f4ab83e1/msbuild/targets/SixLabors.Global.targets) file could be deleted since its sole purpose is to add support for `InternalsVisibleTo` items.

You can see it when compiling a project using the shared infrastructure such as SixLabors.Fonts. The assembly attributes end up in both `artifacts\obj\src\SixLabors.Fonts\Debug\*\SixLabors.Fonts.AssemblyInfo.cs` and `artifacts\obj\src\SixLabors.Fonts\Debug\*\SixLabors.Fonts.InternalsVisibleTo.cs` when using a recent .NET SDK.

Except for `InternalsVisibleTo` vs `InternalsVisibleToAttribute`, the are effectively identical in both files:

```csharp
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(@"DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(@"SixLabors.Fonts.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001000147e6fe6766715eec6cfed61f1e7dcdbf69748a3e355c67e9d8dfd953acab1d5e012ba34b23308166fdc61ee1d0390d5f36d814a6091dd4b5ed9eda5a26afced924c683b4bfb4b3d64b0586a57eff9f02b1f84e3cb0ddd518bd1697f2c84dcbb97eb8bb5c7801be12112ed0ec86db934b0e9a5171e6bb1384b6d2f7d54dfa97")]
```

**Comment by JimBobSquarePants** [comment]
Thanks. We’re aware of the .NET 5+ support. 
We unit test by compiling the library against individual target framework SDKs most of which do not support the properties.
